version: '3.4'
services:
  databasepg:
    container_name: databasepg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"